INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Hairy-eared dwarf lemur','Allocebus trichotis','Endangered','Decreasing','Small','Northeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Eastern Woolly Lemur','Avahi laniger','Vulnerable','Decreasing','Medium','Northeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Southern Woolly Lemur','Avahi meridionalis','Endangered','Decreasing','Medium','Southeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Western Wooly Lemur','Avahi occidentalis','Vulnerable','Decreasing','Medium','Northwest');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Sambirano Wooly Lemur','Avahi unicolor','Critically Endangered','Decreasing','Medium','Northwest');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Bemaraha Wooly Lemur','Avahi cleesei','Critically Endangered','Decreasing','Medium','West');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Betsileo Wooly Lemur','Avahi betsileo','Endangered','Decreasing','Medium','East');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Moore''s Wooly Lemur','Avahi mooreorum','Endangered','Decreasing','Medium','Northeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Western Wooly Lemur','Avahi ramanantsoavanai','Vulnerable','Decreasing','Medium','Southeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Aye-aye','Daubentonia madagascariensis','Endangered','Decreasing','Small','East');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('White-Collared Lemur','Eulemur cinereiceps','Critically Endangered','Decreasing','Medium','Southeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Collared Brown Lemur','Eulemur collaris','Endangered','Decreasing','Medium','Southeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Blue-eyed Black Lemur','Eulemur flavifrons','Critically Endangered','Decreasing','Medium','Northwest');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Mongoose Lemur','Eulemur mongoz','Critically Endangered','Decreasing','Medium','Northwest');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Lac Alaotra Bamboo Lemur','Hapalemur alaotrensis','Critically Endangered','Decreasing','Medium','Northeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Golden Bamboo Lemur','Hapalemur aureus','Critically Endangered','Decreasing','Medium','Southeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Eastern Lesser Bamboo Lemur','Hapalemur griseus griseus','Vulnerable','Decreasing','Medium','East');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Eastern Lesser Bamboo Lemur','Hapalemur griseus ranomafanensis','Vulnerable','Decreasing','Medium','West');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Rusty-gray Lesser Bamboo Lemur','Hapalemur meridionalis','Vulnerable','Decreasing','Medium','Southeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Western Lesser Bamboo Lemur','Hapalemur occidentalis','Vulnerable','Decreasing','Medium','North');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Indri(Babakoto)','Indri indri','Critically Endangered','Decreasing','Large','Northeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Ring-tailed Lemur','Lemur catta','Endangered','Decreasing','Medium','South');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Milne-Edwards''s Sportive Lemur','Lepilemur edwardsi','Endangered','Decreasing','Small','Northwest');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('White-Footed Sportive Lemur','Lepilemur leucopus','Endangered','Decreasing','Small','Southeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Small-Toothed Sportive Lemur','Lepilemur microdon','Endangered','Decreasing','Small','Southeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Weasel Sportive Lemur','Lepilemur mustelinus','Vulnerable','Decreasing','Small','Northeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Red-Tailed Sportive Lemur','Lepilemur ruficaudatus','Critically Endangered','Decreasing','Small','East');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Sahamalaza Sportive Lemur','Lepilemur sahamalazensis','Critically Endangered','Decreasing','Small','Northwest');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Sahafary Sportive Lemur','Lepilemur septentrionalis','Critically Endangered','Decreasing','Small','Northeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Madame Berthe''s Mouse Lemur','Microcebus berthae','Critically Endangered','Decreasing','Small','West');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Gray-Brown Mouse Lemur','Microcebus griseorufus','Least Concern','Decreasing','Small','South');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Gray Mouse Lemur','Microcebus murinus','Least Concern','Decreasing','Small','West');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Pygmy Mouse Lemur','Microcebus myoxinus','Vulnerable','Decreasing','Small','Northwest');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Brown Mouse Lemur','Microcebus rufus','Vulnerable','Decreasing','Small','Southeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Greater Bamboo Lemur','Prolemur simus','Critically Endangered','Decreasing','Medium','East');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Silky Sifaka','Propithecus candidus','Critically Endangered','Decreasing','Medium','North');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Coquerel''s Sifaka','Propithecus coquereli','Critically Endangered','Decreasing','Medium','Northwest');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Diademed Sifaka','Propithecus diadema','Critically Endangered','Decreasing','Medium','Northeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Milne-Edwards''s Sifaka','Propithecus edwardsi','Endangered','Decreasing','Medium','East');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Perrier''s Sifaka','Propithecus perrieri','Critically Endangered','Decreasing','Medium','Northeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Golden-Crowned Sifaka','Propithecus tattersalli','Critically Endangered','Decreasing','Small-Medium','Northeast');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Verreaux''s Sifaka','Propithecus verreauxi','Critically Endangered','Decreasing','Medium','South');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Red Ruffed Lemur','Varecia variegata rubra','Critically Endangered','Decreasing','Medium','East');
INSERT INTO species(name, Scientific_name, iucn_category, population_trend, size, area) VALUES ('Black-and-white ruffed lemur','Varecia variegata variegata','Critically Endangered','Decreasing','Medium','East');